services:
  postgres:
    container_name: hairday_db
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=database
