name: hello-world
on: 
  push:
   branches:
    - develop
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Hello world"
